"""ADR draft generator for orphaned decision nodes."""

from __future__ import annotations

from datetime import date

from ..schema import Decision, GraphNode
from .logger import get_logger
from .state import get_state

logger = get_logger(__name__)


def _format_alternatives(alternatives: list[str]) -> str:
    if not alternatives:
        return "- (none recorded)\n"
    return "".join(f"- {alt}\n" for alt in alternatives)


def generate_adr(node: GraphNode) -> str:
    """Generate a draft ADR markdown string from a graph node.

    Uses a template fallback suitable for hackathon demos. Swap the body for an
    LLM prompt when ``LLM_API_KEY`` is available.
    """
    title = getattr(node, "title", None) or node.text[:80]
    status = getattr(node, "status", None)
    status_text = status.value if status is not None else "proposed"
    decided_on = getattr(node, "decided_on", None) or date.today()
    alternatives = getattr(node, "alternatives", []) or []
    confidence = getattr(node, "confidence", None)
    confidence_text = confidence.value if confidence is not None else "unknown"

    markdown = f"""# ADR Draft: {title}

Status: {status_text}

Date: {decided_on}

## Context

{node.text}

This draft was auto-generated because the decision node was flagged as orphaned
(confidence: {confidence_text}). Review and promote to a formal ADR if the
reasoning should be preserved.

## Decision

{title}

## Alternatives considered

{_format_alternatives(alternatives)}

## Consequences

- Requires manual review before acceptance.
- Generated by Archeon lifecycle engine to prevent silent knowledge loss.

## Metadata

- Node ID: {node.id}
- Node type: {node.type.value}
"""

    get_state().record_adr(node.id, title, markdown)
    logger.info("ADR generated for node %s: %s", node.id, title)
    return markdown
